name: Checkout

run-name: Checkout

on:
    push:

jobs:
    checkout-and-display-files:
        name: Checkout & Display Files
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List Files After
              run: ls -a

    simple-action:
        name: Simple Checkout Action
        runs-on: ubuntu-latest
        steps:
            - name: Simple JS Action
              uses: actions/checkout@v4
    
    simple-custom-action-v1:
        name: Simple Custom Action (Version 1)
        runs-on: ubuntu-latest
        steps:
            - name: Simple Custom JS Action
              id: greet
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: Jackie Chan
            - name: Log Greeting Time
              run: echo "${{ steps.greet.outputs.time }}"

    simple-custom-action-v2:
        name: Simple Custom Action (Version 2)
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Run Simple Custom JS Action
              id: basedCustom
              uses: ./.github/custom-action
            - name: Print Result
              run: echo "Message:${{ steps.basedCustom.outputs.message }}"