name: Repository Events

run-name: Repository Events

on:
    push:
        branches:
            - main
            - "feature/*" # any branch that starts with the word feature/
            - "feature/**" # any branch that starts with the word feature/ and more
        tags: 
            - v1.* # match any tags that start with v1
            - "!v1.1.1"
        paths:
            - "**.js"
            - "!app.js"
    pull_request:
        types: [opened, assigned, reopened, synchronize]
        branches:
            - main
        paths:
            - "**.js"
    issues:
        types: [opened, closed]

jobs:
    checkout-test:
        name: Checkout Test
        runs-on: ubuntu-latest
        steps:
            - name: Print Info
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - name: Checkout Code
              uses: actions/checkout@v3