name: Expressions & Contexts

run-name: "Expressions & Contexts By @${{ github.actor }}, event: ${{ github.event_name }}"

on:
    - push
    - pull_request
    - issues
    - workflow_dispatch

jobs:
    using-expressions-and-contexts:
        name: Using Expressions & Contexts
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: Expressions
              id: expressions
              run: |
                echo ${{ 1 }}
                echo ${{ 'This is a string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1 > 2 }}
                echo ${{ 'string' == 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}
            - name: Dump Contexts
              run: |
                echo '***GITHUB SECTION***'
                echo '${{ toJson(github) }}'
                echo ''
                echo '***JOB SECTION***'
                echo '${{ toJson(job) }}'
                echo ''
                echo '***SECRETS SECTION***'
                echo '${{ toJson(secrets) }}'
                echo ''
                echo '***STEPS SECTION***'
                echo '${{ toJson(steps) }}'
                echo ''
                echo '***RUNNER SECTION***'
                echo '${{ toJson(runner) }}'
    
    document-issue:
        name: Document Issue
        runs-on: ubuntu-latest
        needs: using-expressions-and-contexts
        if: github.event_name == 'issues'
        steps:
            - name: Print issue context
              run: echo '${{ toJson(github.event_name) }}'