name: Hello World Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World My Guy"
        shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye World
        run: echo "Goodbye World Mayne!"
        shell: bash
    
