name: Workflow Commands

run-name: Workflow Commands

on:
    push:

jobs:
    testing-wf-commands:
        name: Testing Workflow Commands
        runs-on: ubuntu-latest
        steps:
            - name: Setting An Error Message
              id: error-message
              run: echo "err=This is a BASED error message!" >> "$GITHUB_OUTPUT"
            - name: Printing An Error Message
              run: echo "::error::${{ steps.error-message.outputs.err }}"
            - name: Group Of Logs
              run: |
                echo "::group::My Group Title"
                echo "Inside Group"
                echo "::endgroup::"
            - name: Masking A Value
              run: echo "::add-mask::Ohio"
            - name: Echo A Secret
              run: echo "My secret is that I am BASED like Ohio"