name: Working Directory & Shells

run-name: Working Directory & Shells

defaults:
    run:
        shell: bash

on:
    push:

jobs:
    display-wd-info:
        name: Display WD Info
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change Working Dir
              working-directory: /home/runner
              run: pwd

    display-wd-info-windows:
        name: Display WD Info (Windows)
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display Working Directory & List Files (Windows)
              run: |
                ${PWD}
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Python Shell
              shell: python
              run: |
                import platform
                print (platform.processor())